version: "3.8"

services:
  db:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:
